name: Development_environment_deployment

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Deploy
      working-directory: ./sword-test
      run: |
        git clean -f
        git pull
        npm i
        npm run build
        npm run migration:generate migrate
        npm run migration:up >> $GITHUB_ENV
        pm2 restart all
        curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d text='Backend deployment was successful'
    - name: check
      run:  echo $GITHUB_ENV
      
